name: CI

on: pull_request

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # TODO: Enable the test step once tests are implemented or ready to run
      # - name: Run tests
      #   run: pnpm test:run

      - name: Run TypeScript type checking
        run: pnpm type-check

      - name: Check for remaining ESLint errors
        run: pnpm lint

      - name: Check for remaining formatting issues
        run: pnpm format:check
